[AnticheatConf]
ConfVersion=2017102301
Enable = 0
FingerprintHistory = 30
FingerprintLevel = 6
KickDelay.Min = 30
KickDelay.Max = 90
BanDelay.Min = 30
BanDelay.Max = 90
IPBanDelay.Min = 30
IPBanDelay.Max = 90
BanWave.Day = 1
BanWave.Hour = 10
BanWave.Minute = 0
