#################################
# Turtle WoW Configuration file #
#################################

[MangosdConf]
ConfVersion=2010100901

RealmID = 1
DataDir = "../data"
LogsDir = "../logs/"
HonorDir = "../honor"
HardcoreModeLogFile = "hardcore.log"
LogMailAH = "auction.log"

# Database connection settings
LoginDatabase.Info = "mariadb;3306;root;mangos;tw_logon"
WorldDatabase.Info = "mariadb;3306;root;mangos;tw_world"
CharacterDatabase.Info = "mariadb;3306;root;mangos;tw_char"
LogsDatabase.Info = "mariadb;3306;root;mangos;tw_logs"

LoginDatabase.Connections = 4
WorldDatabase.Connections = 1
CharacterDatabase.Connections = 10
LogsDatabase.Connections = 2

# DB Auto-updater
Database.AutoUpdate.Enabled = 1
Database.AutoUpdate.Path = "../sql/"
Database.AutoUpdate.AuthUpdateName = "unused"
Database.AutoUpdate.CharUpdateName = "unused"
Database.AutoUpdate.WorldUpdateName = "database_updates"
DBUpdaterLogFile = "dbupdates.log"
AutoCommit.Minutes = 60

LoginDatabase.WorkerThreads = 2
WorldDatabase.WorkerThreads = 1
CharacterDatabase.WorkerThreads = 4
LogsDatabase.WorkerThreads = 6

MaxPingTime = 30
WorldServerPort = 8091
BindIP = "0.0.0.0"
UseProcessors = 0
ProcessPriority = 1
Compression = 1
PlayerLimit = 0
PlayerHardLimit = 4096
LoginQueue.GracePeriodSecs = 10
LoginPerTick = 8
CharacterScreenMaxIdleTime = 900
SaveRespawnTimeImmediately = 1
MaxOverspeedPings = 2
