########################################
# Turtle WoW realmd configuration file #
########################################

[RealmdConf]
ConfVersion=2010062001

# REALMD SETTINGS
#    LoginDatabaseInfo
#         Database connection settings for the realm server.
#         Format: hostname;port;username;password;database

LoginDatabaseInfo = "mariadb;3306;root;mangos;tw_logon"

LogsDir = "/app/logs/"
MaxPingTime = 3
RealmServerPort = 3724
BindIP = "0.0.0.0"
PidFile = "twrealmd.pid"
LogLevel = 1
LogTime = 0
LogFile = "realmd.log"
LogTimestamp = 0
LogFileLevel = 3
LogColors = ""
UseProcessors = 0
ProcessPriority = 1
WaitAtStartupError = 0
MinRealmListDelay = 1
RealmsStateUpdateDelay = 10
WrongPass.MaxCount = 10
WrongPass.BanTime = 300
WrongPass.BanType = 0
ReqEmailVerification = 0
ReqEmailSince = 0
GeoLocking = 0
StrictVersionCheck = 0
SendMail = 0
MailFrom = "no-reply@turtle-wow.org"
MailCertChecks = 1
SendGridKey = ""
GeolockGUID = ""
HostAddressOverride = "0.0.0.0"
ForcePinAccountRank = 5
